<?php
/**
 * SuccessResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ravex Partner API
 *
 * Business-facing API for airtime, data, bills, betting, giftcards, and bank transfers.  ## Wallet Model  Each business has two wallets: - **NGN wallet** — powers all transactional services (airtime, data, electricity, cable, bet funding, giftcard buy/sell, bank transfer) - **USD wallet** — reserved for the Dollar Card service (coming soon). Funded only by converting from the NGN wallet at the admin-configured rate. USD cannot be converted back to NGN.  Use `GET /balance` to check both wallet balances. Use `POST /wallet/convert-to-usd` to convert NGN → USD.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ravex.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SuccessResponseTest Class Doc Comment
 *
 * @category    Class
 * @description SuccessResponse
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SuccessResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SuccessResponse"
     */
    public function testSuccessResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
